# Generated by Django 3.1.14 on 2022-03-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_Name', models.CharField(max_length=500)),
                ('Add_File', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Total_Option', models.IntegerField()),
                ('Option_1', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_2', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_3', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_4', models.CharField(blank=True, max_length=500, null=True)),
                ('Option_5', models.CharField(blank=True, max_length=500, null=True)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
        migrations.CreateModel(
            name='DateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('If_Yes', models.TextField()),
                ('If_No', models.TextField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
        migrations.CreateModel(
            name='AddressQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500)),
                ('Locality', models.CharField(max_length=500)),
                ('Pin_Code', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.document')),
            ],
        ),
    ]
