# Generated by Django 3.1.14 on 2022-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanquestion',
            name='Variable',
            field=models.CharField(default='$bool', max_length=50),
        ),
        migrations.AddField(
            model_name='conditionalquestion',
            name='Variable',
            field=models.CharField(default='$condition', max_length=50),
        ),
        migrations.AddField(
            model_name='datequestion',
            name='Variable',
            field=models.CharField(default='$date', max_length=50),
        ),
        migrations.AddField(
            model_name='optionalquestion',
            name='Variable',
            field=models.CharField(default='$optional', max_length=50),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='Variable',
            field=models.CharField(default='$text', max_length=50),
        ),
    ]
