# Generated by Django 3.1.14 on 2022-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220312_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressquestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressquestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booleanquestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booleanquestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditionalquestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditionalquestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datequestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datequestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optionalquestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optionalquestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='Captialize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='Double_Quotes',
            field=models.BooleanField(default=False),
        ),
    ]
