# Generated by Django 3.1.14 on 2022-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20220316_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressquestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booleanquestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditionalquestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datequestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optionalquestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='Question_Number',
            field=models.IntegerField(default=0),
        ),
    ]
